language: go
services:
- mysql
- postgres
- redis-server
addons:
  postgresql: '9.4'
go:
- '1.7'
- '1.8'
- '1.9'
- tip
go_import_path: github.com/stellar/go
install:
- wget https://github.com/Masterminds/glide/releases/download/v0.12.3/glide-v0.12.3-linux-amd64.tar.gz
- tar -xzvf glide-v0.12.3-linux-amd64.tar.gz
- cp linux-amd64/glide $GOPATH/bin
script:
- glide install
- ./support/scripts/run_tests
before_deploy:
- go run ./support/scripts/build_release_artifacts/main.go
  #adopted from https://stackoverflow.com/questions/28217556/travis-ci-auto
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- git tag -d snapshots || true
- git push --delete -q https://$GITHUB_OAUTH_TOKEN@github.com/stellar/go sn
- git tag snapshots -a -m "Generated snapshots from TravisCI for build $TRAT')"
- git push -q https://$GITHUB_OAUTH_TOKEN@github.com/stellar/go --tags
matrix:
  fast_finish: true
  allow_failures:
  - go: tip
notifications:
  slack:
    on_success: change
    on_failure: always
    secure: Uhx8H2RFNsJ9GknDItSwhMOl5K3HTGNjifJwkLUiRio4JH4PzrkHDOzCOpEzrborfNCmW8bTcGydeVOe0HV18mpM/4yPy/gsw5Zq+eGq7+p9NZtwkOHeQ/YtoSFcWbQQYs3CPZpBUPl2uraHdjg5EUJJO/4yR0GWC1pLTfUCqUt9mXPeGSQOhhvR+pCKSljY3pB6oex2hKH04u3U1iRzOEk1a1n27wzjqYlDeH4xaYTZGpB18LiX6MAm84+iviL5JILIMQ4NcqVNB2L37zl1UW+BMQUSH6+zwztzxhJOz6PAE1aA3O+BI1xuSft6sGY07Z0Q9iKO/uCWIHbsfLso16kIubiHzwjSAz90tbCc8VcwWPXCg8mRFCCuXgr4dev7I+vKcx43oIddgcx6vIROMYsgX/0gInBrkNxZw3Gu1YUXe1fuNvmCZWMYBQrH18sxU=
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: q8H6HZWdaVF9lW2svzV/xdVZzF8SOBrnqGleAXEtI8l9bykq6gWBxSrU4BSma3KgPgaOD6Jz+jr62VNlRr4eWot+UZNTvuJMbR/3qqzMee5pIqIjI2kmDYD6VnOB0vAK3It/JCIc+VvXUGJ0cUDjKF1aiHKCFcWfkNUlTQoPnItpGNzBzGoTOX06LR9X+Uf9w651za+vZ7c0Ftd/AujvvWjHz/C2O56Ybi5V9TkKG3Yjy6eNVt7txhq1BY2A4EwvX8Lf8zMiG2VQ0YMNM1qUV6LDjqq4uCOe2Ue6XHYtk1pJVgWJwImnMbxNArEWWe2gt8ZL5vk21Q1VJN4bF2o2o94j/OjC/Nrawb9wgJN6tcX3xa8bjGTmG+wTCWGkIRg1uX5EqbOqU1pP9lUPPknstfEi3w30ZR/4wnOrfXBh8fjfxZnTz6S32yLcmzGqn78L4=
  file: dist/*
  file_glob: true
  overwrite: true
  prerelease: true
  tags: false
  name: Snapshots $(date --utc +'%F-%T')
  on:
    branch: master
    go: '1.8'
